spring.application.name=randomcontextmemories

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:random_context_memories}
spring.datasource.username=${POSTGRES_USER:rcm_app}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false